---
title: "project"
output: html_document
---
```{r, warning = FALSE, message = FALSE}
library(leaflet)
library(magrittr)
library(tigris)
library(acs)
library(dplyr)
library(stringr)
```

###Median Age by Zip Code:


###Ancestry:

```{r, echo = FALSE}
counties <- c(5, 47, 61, 81, 85)
#gives the spatial thing using tigris
tracts <- tracts(state = 'NY', county = c(5, 47, 61, 81), cb=TRUE)
#acs data extraction:
geo<-geo.make(state=c("NY"),
              county=c(5, 47, 61, 81), tract="*", check = TRUE)

ancestry=acs.fetch(geo=geo, table.name="People Reporting Ancestry",
                   col.names="pretty")

anc <- ancestry@estimate
anc <- data.frame(anc)

colnames(anc) <- lapply(colnames(anc), function(x){str_split(x, "Ancestry...")[[1]][2]})

colnames(anc) <- lapply(colnames(anc), function(x) {gsub(".", "", x, 
                                                         fixed = TRUE)})


geoid <- paste0(str_pad(ancestry@geography$state, 2, "left", pad="0"), 
                              str_pad(ancestry@geography$county, 3, "left", pad="0"), 
                              str_pad(ancestry@geography$tract, 6, "left", pad="0"))


anc$geoid <- geoid

eth <- numeric(2057)

for (i in (1:2057)){
eth[i] <- names(which.max(anc[i,-c(1, 108, 109, 110)]))
}

anc$eth <- eth

final.df <- data.frame(anc$geoid, stat = as.factor(anc$eth))

merge<- geo_join(tracts, final.df, "GEOID", "anc.geoid")

pal <- colorFactor("Paired", NULL, n = 6)

leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(data = merge, 
                fillColor = ~pal(stat), fillOpacity = .65, 
                color = "white", weight = .5,
                popup = paste0(merge$stat)) %>%
    addLegend(pal = pal, 
              values = merge$stat, 
              position = "bottomright",
              opacity = .7,
              title = "Ancestry")
```

###Map of Biking:

```{r, echo = FALSE}

#data munging
bikes <- read.csv("transport_zip.csv", stringsAsFactors = FALSE)
bikes <- select(bikes, zip = GEO.display.label, total = HD01_VD01, 
                bike = HD01_VD18)
bikes <- bikes[-1,]
bikes$zip <- unlist(lapply(bikes$zip, function(x){str_split(x, " ")[[1]][2]}))
bikes$stat <- round(as.numeric(bikes$bike)/as.numeric(bikes$total)*100,2)


final.df <- select(bikes, zip, stat)

codes <- c("100","101","102","103","104","111","112","113","114")
#"070","071","072","073")

zips <- zctas(cb = TRUE, starts_with = codes) #tigris

merge <- geo_join(zips, final.df, "ZCTA5CE10", "zip") #tigris

pal <- colorNumeric(c("Blues"), domain = -1:8)


leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -74.0059, lat = 40.7127, zoom = 13) %>%
    addPolygons(data = merge, fillColor = ~pal(stat), fillOpacity = .6, 
                color = "white", weight = 1.5,
                popup = paste0(merge$stat, "% biking to work")) %>%
    addLegend(pal = pal, 
              values = merge$stat, 
              position = "bottomright",
              opacity = .7,
              title = paste0("Percentage of People <br> Biking to Work"))



```